name: Periodic health check

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  schedule:
    #- cron: '1,11,21,31,41,51 * * * *'  # runs on minutes: 1, 11, ...
    - cron: '33 3 * * *'  # runs at 03:33

jobs:
  check_deployed_service_URL:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          # Check the following URLs one by one sequentially
          url: https://full-stack-open-pokedex-19aa.onrender.com