name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  CONDITION_SKIP: ${{ contains(join(github.event.commits.*.message), '#skip') }}

jobs:
  skipping_delivery_and_tagging:
    runs-on: ubuntu-20.04
    steps:
      - name: not pull request?
        if: ${{ github.event_name != 'push' }}
        run: echo "skipping delivery&tagging as not merge pull request"
      - name: skipping as '#skip' included?
        if: ${{ github.event_name == 'push' && env.CONDITION_SKIP != 'false' }}
        run: echo "skipping delivery&tagging as '#skip' included in the commit title"
      - name: delivery and tagging going ahead?
        if: ${{ github.event_name == 'push' && env.CONDITION_SKIP == 'false' }}
        run: echo "delivery and tagging going ahead"
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && env.CONDITION_SKIP == 'false' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Send Discord notification
        uses: stegzilla/discord-notify@v2
        if: ${{ success() && github.event_name == 'push' && env.CONDITION_SKIP == 'false'}}
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: New version of Pokedex deployed (tph)
          message: "**${{ github.event.head_commit.message }}**\n**Creator:** ${{ github.event.push.head_commit.committer.name }}\n${{ github.event.push.head_commit.url }}"
      - name: event variables
        run: echo ${{ github.event.push.head_commit.message }}
      - name: event variables 3
        run: echo '${{toJSON(github.event)}}'
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && env.CONDITION_SKIP == 'false' }}
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}