name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  COMMIT_MESSAGES: ${{ join(github.event.commits.*.message) }}
  CONDITION_SKIP: ${{ contains(COMMIT_MESSAGES), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && env.CONDITION_SKIP == 'false' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - name: kokeillaan skipillä, uusi yritys
        run: echo "kokeillaan skipillä. onko condition true"
      - uses: actions/checkout@v4
      - name: commit messages
        run: echo "$COMMIT_MESSAGES"
      - name: condition skip
        run: echo "$CONDITION_SKIP"
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && env.CONDITION_SKIP == 'false' }}
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}